apiVersion: v1
kind: Service
metadata:
  name: invoker
  labels:
    app: invoker
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 18000
    - name: http-x
      port: 8080
      targetPort: 8080
  selector:
    app: invoker
