apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - invoker-pod.yaml
  - invoker-service.yaml
  - xds-pod.yaml
  - xds-service.yaml

configMapGenerator:
- name: manifest-config
  files:
  - manifest.yaml
- name: envoy-config
  files:
    - envoy-xds-config.yaml
